/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

function requiredPublicEnv(name: string) {
  const value = import.meta.env[name];
  if (!value) {
    throw new Error(`Falta configurar ${name} en el ambiente de la app.`);
  }
  return value;
}

export const supabaseUrl = requiredPublicEnv("VITE_SUPABASE_URL");
export const supabaseFunctionsBaseUrl =
  import.meta.env.VITE_SUPABASE_FUNCTIONS_BASE_URL ||
  `${supabaseUrl}/functions/v1`;
export const projectId = supabaseUrl.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1] || "";
export const publicAnonKey = requiredPublicEnv("VITE_SUPABASE_ANON_KEY");
export const googleMapsApiKey = import.meta.env.VITE_GOOGLE_MAPS_API_KEY || "";
export const copomexToken = import.meta.env.VITE_COPOMEX_TOKEN || "pruebas";
