/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

function requiredPublicEnv(name: string) {
  const value = cleanPublicEnv(import.meta.env[name]);
  if (!value) {
    throw new Error(`Falta configurar ${name} en el ambiente de la app.`);
  }
  return value;
}

function cleanPublicEnv(value: unknown) {
  const normalized = String(value || "").trim();
  return normalized.startsWith("=http") ? normalized.slice(1) : normalized;
}

export const supabaseUrl = requiredPublicEnv("VITE_SUPABASE_URL");
export const supabaseFunctionsBaseUrl =
  cleanPublicEnv(import.meta.env.VITE_SUPABASE_FUNCTIONS_BASE_URL) ||
  `${supabaseUrl}/functions/v1`;
export const projectId = supabaseUrl.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1] || "";
export const publicAnonKey = requiredPublicEnv("VITE_SUPABASE_ANON_KEY");
export const mapboxAccessToken = import.meta.env.VITE_MAPBOX_ACCESS_TOKEN || "";
export const copomexToken = import.meta.env.VITE_COPOMEX_TOKEN || "pruebas";
