/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL || "https://ssnfoheivrzhbfsrnswi.supabase.co";
export const supabaseFunctionsBaseUrl =
  import.meta.env.VITE_SUPABASE_FUNCTIONS_BASE_URL ||
  `${supabaseUrl}/functions/v1`;
export const projectId = supabaseUrl.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1] || "ssnfoheivrzhbfsrnswi";
export const publicAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY || "sb_publishable_LwDAFknte9hiBU1fs9os9g_jr-_YHxM";
